### ISSUE TITLE
bug in run_the_model.py and some examples I'd like to do

### ISSUE THREAD

**Issue by francispoulin** [pyqg/pyqg#20]
I finally found the time to look at the BT QG problem and am very impressed with the code.  When I try run_the_model.py I get an error because beta1 is not known,

Francis-Poulins-MacBook-Pro:examples fpoulin$ /Applications/anaconda/bin/python run_the_model.py 
Traceback (most recent call last):
  File "run_the_model.py", line 9, in <module>
    imshow(m.q[0] + m.beta1 * m.y)
AttributeError: 'QGModel' object has no attribute 'beta1'

If I go into the code and change the two instances of beta1 to beta than that does the trick.

It runs but it plots the image in such a way that you need to close each frame.  I wonder if it might be easier to use plt.draw() so that it runs automatically.

Also, there are a few examples that I thought I might try to put together, hopefully soon.

1) Take your BT QG model and switch on beta to hopefully generate zonal jets a la Rhines.  I have tried doing this before with some success but if anyone has tried this and has nice parameters that would be welcome.  Or I could also revisit Peter's original paper.

2) An SQG model.  Mostly everything is the same but I need to change the inversion.  If I do that then would it make sense to have something called sqg_model.py?

3) This is more ambitious, but if I wanted to use this code to study the stability of a Bickley jet, as Glenn did in 87 or so, because the streamfunction of the basic state is not periodic, it would be necessary to decompose the background state and the perturbation.  Before I try this do you foresee any problems?

**Comment by crocha700** [comment]
Thanks for testing it out!

Note that run_the_model.py was actually an old example that runs the 2layer model.  I just pushed a commit fixing the beta1 thing and also adding some examples that run the bt model with snapshots (see McWilliam1984.py, RW.py, Jets.py). Note that you can open IPython allowing matplotlib in order to avoid having to close the frame:

$ ipython --matplotlib

Yes, I think we should populate the "examples" directory well-known results. That will help us testing and documenting this code. (The Jets.py example to have elongated feature in PV anomalies, but to get nicer jets, it would be important to include some forcing, and then run forced-dissipative simulations.) We should also include for a QG topography.

Yes, the adaptation to a SQG model subclass is easy (just change kappa^2 with something like coth[N/f0 kappa H] / kappa ), though perhaps it would be better to get this as a special case of a Eady-type model, with two surfaces.

**Comment by francispoulin** [comment]
Thanks for adding those examples. They look great.

As for the plotting, this is something that might depend on what backend you are using.  By default my laptop uses MacOSX, no surprise.  In order to get an animation I do something like this,

plt.ion()

for snapshot in m.run_with_snapshots(tsnapstart=0, tsnapint=200*m.dt):
    plt.clf()
    plt.imshow(m.q + m.beta * m.y)
    plt.clim([-20., 130.])
    plt.draw()
    #plt.title(str(m.t))
    plt.pause(0.01)

plt.ioff()
plt.show()

The 3 differences are plt.ion() before, I switched show() to draw() in the loop, and then after the loop, I want to see the image so I added the last two lines.  

I realize this is a matter of taste.  But if you suggest a better backend that would work more easily for the animations I am happy to try it out.

For SQG we just need to change the inversion.  You are right that if we wanted a bottom than it is a hyperbolic tangent function.  If we don't mind having an infinite bottom then we simply multiply by the wavenumber instead of dividing by the wavenumber squared.  I will try and do this and hopefully convince myself that it is in fact that easy.  We can certainly generalize this later if we like.

**Comment by rabernat** [comment]
So is this a bug or can it be closed?

**Comment by rabernat** [comment]
No response so I am closing this.
