### ISSUE TITLE
error in spectral divergence term of do_advection

### ISSUE THREAD

**Issue by worthamc** [pyqg/pyqg#202]
There is an error with ikQy in the spectral divergence part of _do_advection.  The spectral divergence is computed in spectral space, but the ikQy term is in physical space.  This doesn't matter for spatially uniform Ubg, but with a zonal jet this will be wrong.  

I think @navidcy said he has some notes on the proper term here.

**Comment by navidcy** [comment]
My (very brief) notes on implementing a y-varying mean flow `U(y)` are here:
https://fourierflows.github.io/GeophysicalFlows.jl/latest/modules/multilayerqg/

If you have a mean flow `U(y)` then it is its stream function that appears in the basic PV state, `\int^y U(y') dy'`. To overcome this, what me and @glwagner do in `GeophysicalFlows.jl` is to ask the user to prescribe `U(y)` and then compute the mean PV gradients `Q_x` and `Q_y` (which include also the β terms the topographic PV gradients.


Regarding tests, a solid test for all the nonlinear terms is the following:

Assume a given basic state `U_n(y)` and a given perturbation flow, `q_n(x, y)`. Compute the nonlinear advection terms *analytically*, `J(Ψ_n, Q_n)`. Then construct a forcing function `F_n` using this analytically computed nonlinear terms in such way that a solution of the problem is `q_n(x, y)`. (Basically you arrange your forcing in such way that it cancels the nonlinear terms in the advection.) If the numerics calculate the nonlinear terms correctly then starting from `q_n(x, y)` and  time-stepping the problem for few time steps would leave the solution unchanged. 

This test would have caught the bug described above.

Such a test for the nonlinear advection terms is found, e.g., here for the barotropic QG module:
https://github.com/FourierFlows/GeophysicalFlows.jl/blob/2cdcf6ddd65de04e997d369c34a1cd9497b44e8b/test/test_barotropicqg.jl#L199

**Comment by navidcy** [comment]
I tried to dig in the code to resolve this as I understood the `do_advection` is part of the `kernel.pyx` cython code with which I don't feel so comfortable with...
