### ISSUE TITLE
xarray 

### ISSUE THREAD

**Issue by MFJansen** [pyqg/pyqg#259]
Apparently conda will install the latest version of pyqg without checking for xarray.  I'm not an expert on conda packages, but shouldn't it be possible to specify dependency on xarray and make sure conda will install it?

**Comment by rabernat** [comment]
We explicitly decided to make xarray an optional dependency, since it's not strictly required to run the model. It's imported when you call `to_dataset()` here:

https://github.com/pyqg/pyqg/blob/ae3321488259fb62ca14e481fab6de291b5d02b9/pyqg/model.py#L681-L689

Do you think we should make it a hard dependency? Or what about catching an `ImportError` and saying "if you want to use this feature, please install Xarray as follows..."?

**Comment by MFJansen** [comment]
Fair enough. I think catching an in ImportError is a good idea.
Part of the issue right now is that the xarray conversion is being used in the some of the examples in the docs (including in the first one). So people will install pyqg,  try out the first example and immediately get an error thrown at them, which  is a bit unfortunate. (This actually did happen to multiple of my students.) So another thing we could do (ideally in addition to the ImportError) is to just add a comment in the examples that us to_dataset(),noting that this functionality requires xarray.

**Comment by rabernat** [comment]
Really good point Malte. We do not want to have examples in the docs inconsistent with the installation instructions!

**Comment by MFJansen** [comment]
I can add a couple of comments in the example notebooks in the docs (unless you are already on it).

**Comment by rabernat** [comment]
That would be awesome! No I have not started it.
