### ISSUE TITLE
Add automatic linear stability analyis

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#37]
Should be easy. We can just copy Joern's model:
https://github.com/joernc/QGModel/blob/master/model.py

**Comment by crocha700** [comment]
I added a linear stability analysis into model.py (see develop branch) – this does not work with topography or a horizontally sheared mean flow. 

To include topography and horizontally sheared mean flow we have two options:

1. Solve  Nk*Nl  eigenproblems of size (Nx* Ny*Nz)x(Nx* Nx*Nz). This can become impossible if Nx is larger than 64 or 128...
2. Power method: Integrate the linearized equations for some time (just turn off the nonlinear terms) and then estimate the growth rates by fitting a straight line to log(energy) and the getting the eigenstructure as the solution in physical space. Of course, this only allows for the estimation of the most unstable mode (but we're generally interested only in that model anyway).  This seems more practical since we may be interested in the linear equations in other applications.

**Comment by crocha700** [comment]
Is this closed? I'd say that #71 is a separate issue since it will require some important changes (inclusions of horizontally varying U and Qy...)

**Comment by rabernat** [comment]
Yes definitely. It was closed by #115 and I thought I put that in the merge comments. I wonder why it didn't close automatically.
