### ISSUE TITLE
Numerical accuracy in two-layer example, and the multi-layer model

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#74]
I wanted to give a heads up about an accuracy problem. I implemented a multi-layer class, and to test if things were correct I was trying to reproduce some of the results/tests of the two-layer model.  I failed.

 I figured that there's a small (but significant) difference in the inversion matrix. The infinite norm of the difference is O(1.e-5), corresponding to a very small wavenumber (wv2[1,0]), where the matrix we're trying to invert is nearly singular; at very large wavenumbers the differences are O(1e-12).  For the general N-layer model I'm leveraging on np.linalg.inv, whereas in the two-layer model we simply use the matrix that we invert by hand. I checked the matrices we are inverting. They're the same:

From the multi_layer model (m):

````python
In [417]: m.S - np.eye(m.nz)*m.wv2[1,0]
Out[417]: 
array([[ -3.59503397e-09,   3.55555556e-09],
       [  8.88888889e-10,  -9.28367306e-10]])
````

From the two_layer_model (m2):

````python
In [425]: np.array([[-m2.F1-m2.wv2[1,0], m2.F1],[m2.F2,-m2.F2-m2.wv2[1,0]]])
Out[425]: 
array([[ -3.59503397e-09,   3.55555556e-09],
       [  8.88888889e-10,  -9.28367306e-10]])
````

But the results are different:
````python
In [432]: m.a[:,:,1,0]-m2.a[:,:,1,0]
Out[432]: 
array([[  4.76837158e-06,   1.90734863e-05],
       [  4.76837158e-06,   1.52587891e-05]])
````

The problem is that the matrix we're inverting is poorly conditioned, particularly at small wavenumbers. (The determinant is O(1.e-19) !) We're loosing a lot accuracy...

I'm not sure how to circumvent this issue – I tried a few things, but with these numbers it is hard to know what is correct or what to expect. Any thoughts?

(Things get better as we increase the number of layers because the matrix becomes better conditioned.)

**Comment by francispoulin** [comment]
That is strange.  The output of the two matrices are the same so I only have those to go by.  But I did compute the determinant of those matrices and I get a det of -1.81898937148e-11, small but on the same order as the entrices of said matrix.  The det of the difference is O(1e-19) but I don't think that matters.  

You said that for large wavenumbers the differences get to O(1e-12), but for this particular wavenumber the errors must be smaller than O(1e-19) I suspect.

Did you want to show us what all the matrices are in a bad case?  

It seems surprising to me that numerically computing the inverse of a 2x2 matrix is at all different than doing it exactly.  If the det is really O(1e-19), that is pretty much zero by my books, than the matrix is not invertable.  I would think that the exact answer would be flawed as well.

Sorry for all the questions but I am happy to help in figuring this out if you wanted to show us some more details.

**Comment by MFJansen** [comment]
I find a determinant for this matrix of O(10^-19), like Cesar. But I'm not sure that's a problem, since it's mostly a result of the entries in the matrix being O(10^-9) (all else being equal the determinant of a 2x2 matrix scales with the square of the values of the entries). As a thought experiment, you could multiply the matrix by 10^10 before inverting (then the determinant of the matrix you are inverting would be O(10)), and then multiply the inverted matrix again by 10^10. However, since it's all floating point arithmetics, this shouldn't make a difference.

In my understanding, whether a matrix inversion is well conditioned, depends on the ratio of absolute values of the largest to smallest eigenvalue. If I see it correctly that's O(100) here -- maybe not great, but not too bad either...

In the end, I don't see an error of O(10^-5), as a big deal, given that the corresponding values in the inverted matrix are O(10^10) -- that's a relative error of O(10^-15). Am I missing something here?

**Comment by francispoulin** [comment]
My mistake.  I was mixing up the actual matrix and the error.  

When I multiply the matrix by 1e10 I get the determinant is 17.7018170201.

**Comment by crocha700** [comment]
I agree the relative errors are small. But, my point is that the nz=2 case of the multi-layer model will not pass the two_layer tests. I'll press on.

**Comment by rabernat** [comment]
Maybe make a special case for the matrix inversion in the two-layer case? It only has to be done once after all.

**Comment by crocha700** [comment]
Good idea.

**Comment by rabernat** [comment]
Also, try to use numpy.linalg if you can. Right now scipy is not a dependency.
