### ISSUE TITLE
Bug in the kernel: missing negative sign

### ISSUE THREAD

**Issue by crocha700** [pyqg/pyqg#86]
Working on the diagnostics for the layered model, I got confused by the negative sign we use in  http://pyqg.readthedocs.org/en/stable/examples/two-layer.html#plot-diagnostics

I believe this is a bug in the kernel. A missing negative sign in the calculation of the tendencies: 

```{python}
                for i in range(self.Nk):
                    # overwrite the tendency, since the forcing gets called after
                    self.dqhdt[k,j,i] = ( self._ik[i] * self.uqh[k,j,i] +
                                    self._il[j] * self.vqh[k,j,i] +
                                    self._ikQy[k,i] * self.ph[k,j,i] )
```

This should be negative since we are solving

```math_def
q_t = - J(psi,q) 
```

Note that the bottom drag has the correct sign.

**Comment by rabernat** [comment]
A sign error in this core routine would be a pretty big bug. Are you sure? @MFJansen can you weigh in on this?

**Comment by crocha700** [comment]
I think this was introduced in the kernel. It wasn't there in previous versions:
https://github.com/pyqg/pyqg/blob/b5db4bc8d3590c120a5cf5aee3d9bfc24c45903c/pyqg/model.py

See lines 305-308

**Comment by rabernat** [comment]
Hmm... If so, it did not break the tests. Despite our problems with machine-precision reproducibility, I was careful about the tests when switching to the new kernel. I made sure that the solution on my specific machine did not change when switching to the cython kernel.

So there must be some kind of symmetry thing going on here that makes this problem cancel out.

**Comment by rabernat** [comment]
Relevant lines.

Original:
https://github.com/pyqg/pyqg/blob/b5db4bc8d3590c120a5cf5aee3d9bfc24c45903c/pyqg/model.py#L308

Current kernel:
https://github.com/pyqg/pyqg/blob/master/pyqg/kernel.pyx#L373

**Comment by crocha700** [comment]
Yes, this seems only to change the sign of the field! But when we compute diagnostics, say Re[psi^* J(psi,q)], then it shows up!

**Comment by crocha700** [comment]
Where do we stand on this? I fixed this bug in the branch #87 I'm merging into develop.

I also added some documentation regarding the diagnostics: see docs/equations/notation_layered.ipynb --- that also describes N=2 as a special case for the diagnostics. If you focus on the first term on the RHS, you'll see that is the exact same term we compute in qg_model.py. No need to take the negative sign before plotting.

**Comment by rabernat** [comment]
We need @MFJansen to weigh in on this.

**Comment by MFJansen** [comment]
Hey guys, sorry for being slow, I would say I've been super busy, but I guess that's always true for all of us...
I think we really need to understand why our tests didn't fail - we obviously need to have tests that fail if the sign of the advection term is wrong.
As a starting point, so we are all on the same page, here is the relevant check-in where this bug has been introduced:
https://github.com/pyqg/pyqg/commit/baea5113737625e7587b3656a7cf664bc34c5783

Interestingly it seems to me like there were bugs before 
1) the "advect" function ( which apparently was used for the diagnostics) had the wrong sign
2) the Qx term appears to have had the wrong sign (need to look at the full model.py script to see, not just the diff). This term appears to have been removed altogether if I see this correctly.

@crocha700, you are suggesting that the error in the advection term entirely changes only the sign of the solutions? It's unclear to me why that would be the case. The sign of the advection term of course simply changes, but e.g. for non-zero initial conditions (and all else being equal), this should lead to different results (with not just the opposite sign).

**Comment by francispoulin** [comment]
Hello, also sorry for not getting in this sooner.  

If there is a concern about sign could we put together a simple test to convince ourselves one way or another? What if we take the BTModel and fix the velocity such that u = 1 and v =1, it's not exciting, but we know what direction that should go, up and to the right.  Would this be at all helpful?

**Comment by rabernat** [comment]
We do have advection tests. 
https://github.com/pyqg/pyqg/blob/develop/pyqg/tests/test_advection.py#L40

The problem is that they don't actually use the kernel's built in advection. Instead they use the standalone _advect function from the modely.py, which is the same function used by the diagnostics.
https://github.com/pyqg/pyqg/blob/develop/pyqg/model.py#L406

This duplication of the advection routine has contributed to the confusion. As @crocha700 and @MFJansen pointed out above, there was a sign difference between these two routines.

**Comment by francispoulin** [comment]
Thanks for explaining the situation @rabernat.  Sorry that I got a little lost.  I can look at it to see whether I can find an easy way of doing this using the kernel.  Might be more work than it's worth though.

**Comment by rabernat** [comment]
@francispoulin, it doesn't make sense for anyone but @crocha700 to actually implement anything new right now. He is deep into the code right now (see #87). Our role right now is to help him understand the nature of this issue (bug?) and why our testing didn't catch it.

**Comment by MFJansen** [comment]
Actually I'm not sure the diagnostics are all right either. E.g. line 244 in qg_model.py:
 self.Jpxi = self._advect(self.xi, self.u, self.v)
Given that advect is really div(uq), this doesn't look right to me

**Comment by francispoulin** [comment]
I know that @crocha700 did a great job putting together a multi-layer version and I am very keen to learn how to use it, after it's ready of course.  When debugging I always try and reduce things to the simplest possible case, and then build things back up.

I wonder it might be possible to temporarily reduce things back to the one-layer problem.  If we initialize it with a Rossby wave on a beta then it should propagate westward.  Maybe this is too simple though.

**Comment by crocha700** [comment]
Thanks for the feedback guys.

@MFJansen, the sign of the advection change the sign of the solution. Not sure this is the only thing that changes. But the quadratic quantities are definitely unchanged, that's why the tests did not fail. 

Here's how I found out about this issue. I was just getting wrong sign of the diagnostics using the outputs that I saved from run_with_snapshots, and I couldn't get the correct sign for quantities that involved cubic product of perturbation variables (say ph* J(ph, \nabla^2 ph) ). Quadratic quantities were correct. So that's when I realized that in the example two_layer.ipynb we we're taking the negative sign of the diagnostics before plotting.  But when I looked at the code, quantities such as the KE flux spectral div. , we being computed with the correct sign... So I scanned through the code and found this missing negative sign. Changing the sign of the advection (in the Kernel) brings things back to normal. The results are (in a statistical sense) consistent with what we had before. 

The question is why was that negative sign in the diagnostics of two_layer.ipynb introduced?

**Comment by crocha700** [comment]
So the test for advection does not help much in this case since it simply test if that term is zero for a plane wave...

**Comment by rabernat** [comment]
Thanks for the clear explanations @crocha700.

> The question is why was that negative sign in the diagnostics of two_layer.ipynb introduced?

I'm pretty sure this was my fault. I wanted to make the figure match one of Malte's earlier examples, so I think I just stuck the minus signs in without thinking. This was a chance to catch the bug much earlier, but I wasn't worried because the tests were all passing. I figured it was just a plotting issue.

> So the test for advection does not help much in this case since it simply test if that term is zero for a plane wave...

So let's start by rewriting the tests so that they actually do what they are supposed to do. We should have more [unit tests](http://searchsoftwarequality.techtarget.com/definition/unit-testing) in addition to integration tests.

**Comment by crocha700** [comment]
So, I'm not expert in Cython, but could we have a function in the Kernel called "jacobian" or "advection" that simply computes the jacobian between "psih" and a field "fh"? We can then use this function to compute elsewhere in the code (e.g., when computing diagnostics, etc.).

**Comment by MFJansen** [comment]
Ok, I think I'm starting to understand. I still don't believe that the wrong sign in the advection term changes only the sign of the solution: stuff gets advected in the wrong direction - generally that should mean not just a change in the sign of the full solution. However (in a doubly-periodic domain and given a certain symmetry in the initial conditions) it may indeed not change the globally integrated PV variance - which apparently is the only thing that was actually looked at in "test_twolayer_qg"! I thought we are looking at various diagnostics there, but we are actually skipping out of the test before we get there. This may be a good starting point for improving our tests.

Unit tests are nice when searching for the source of an error, but to simply find if anything has changed, I think it may be best to have an actual integration of the model, which makes use of as many components of the model as possible. This actually was a good example of where the unit test for advection passed even though the model was broken (admittedly we had a particularly bad test for the advection, but I think the point still holds that if you want to make sure the model as a whole hasn't changed, running the whole model is the most straightforward way to test.)

**Comment by MFJansen** [comment]
I agree with @crocha700 that it would be desirable to have one advection/jacobian function which gets used both for the actual advection and in the diagnostics.

(However, I'm pretty clueless with regards to implementation -  I don't only know nothing about Cython, but am also no expert in Python or C)

**Comment by rabernat** [comment]
The cython kernel is different from the old implementation because it uses a _fixed data structure_ for the core model fields (``q``, ``qh``, ``u``, ``v``, etc.) Memory is allocated only once for these variables at initialization time. This is more similar to the way, say, a GCM works.

The reason that it is not possible to use the kernel's advection routine for other arbitrary variables is that it is designed to operate on the specific model fields, making the FFT _in place_ from ``uq`` to ``uqh``. Previously, new memory had to be allocated at every timestep for the output of the FFTs. This had a significant computational overhead.

However, it should be no problem to do an advection test directly on the kernel's routine by calling ``m._do_advection()`` directly.
https://github.com/pyqg/pyqg/blob/develop/pyqg/kernel.pyx#L352
This will take whatever is in ``m.u``, ``m.v`` and ``m.q``, multiply them together, take the fft, calculate the divergence in spectral space, and leave the results in ``m.dqhdt``.

The only necessary change would be to add a method for setting ``u`` and ``v`` directly. Currently they are inaccessible from outside cython. This could be done with a ``set`` method here:
https://github.com/pyqg/pyqg/blob/develop/pyqg/kernel.pyx#L501 


```
